# -*- coding: utf-8 -*-
"""Exercício 36

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5Ic01lHXWnS6d3LGCwiCNuadu_FFFgr
"""

n = float(input('Digite o valor da casa: '))
n2 = float(input('Digite o valor do seu salário: '))
n3 = float(input('Digite em quantos anos você almeja pagar: '))
n4 = n3 * 12 # Caucula o tempo
n5 = n2 * 0.30 # Multiplica o salário para ter base dos 30%
n6 = n / n4 # Divide o valor da casa pelo tempo, gerando a parcela.
if n6 > n5: # Se (if) o valor da parcela for maior que (>) o valor que a pessoa pode pagar exibe if ou else.
  print(f'Infelizmente as parcelas {n6:.2f} exederam 30% do seu salário. Seu limite de segurança é R$ {n5:.2f}.')
else:
  print(f'Bacana, o valor da casa é R$ {n:.2f}, o seu salário é R$ {n2:.2f}, você deseja pagar em {n3} anos. Sua aprestação ficou por R$ {n6:.2f}, seu limite de segurança é {n5:.2f} e você pode comprar!')